FROM busybox:musl

COPY [ \
  "./viryaos-grub.tar.gz", \
  "/home/builder/viryaos-grub.tar.gz" \
]

# NOTE: DO NOT ADD ANY MORE LAYERS
#
# Adding additional can increase images size unnecessarily. So, don't do it!
