#!/bin/sh

set -e -x

grub_commit="d34977cb662d9d3c74532dc175103758c47f552f"

# create required directories
rm -rf /root/src/grub-src /root/src/build-cross-aarch64 /root/src/build-x86_64
mkdir -p /root/src/grub-src
mkdir -p /root/src/build-cross-aarch64
mkdir -p /root/src/build-x86_64

# checkout grub and patch grub
cd /root/src/grub-src
git clone https://git.savannah.gnu.org/git/grub.git
cd grub
git checkout -b grub-build $grub_commit

./autogen.sh
./configure --prefix=/usr/local/viryaos-grub --with-platform=efi --target=aarch64-alpine-linux-musl CFLAGS="-Os -Wno-unused-value"
make
make install

# create tarball
cd /usr/local
tar cvf viryaos-grub.tar viryaos-grub
gzip -9v viryaos-grub.tar
mv viryaos-grub.tar.gz /tmp

# cleanup
rm -rf /root/src/grub-src
